version: '3.8'

services:
  crewai-app:
    build: .
    container_name: agentic-engineering-team
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: python main.py